# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v0.10_qt5.ui'
#
# Created: Sat Aug 23 02:21:23 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 606)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(312, 312))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Program_Icon/icons/dnahelixpixels.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MainFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.MainFrame)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.MainFrame, 0, 0, 1, 1)
        self.moreFrame = QtWidgets.QFrame(self.centralwidget)
        self.moreFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.moreFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.moreFrame.setObjectName("moreFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.moreFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.moreFrame)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal) #This is Yeah
        self.splitter.addWidget(self.MainFrame)  #This is Yeah
        self.splitter.addWidget(self.moreFrame) #This is Yeah
        self.gridLayout_3.addWidget(self.splitter, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolTip("")
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setIconSize(QtCore.QSize(35, 35))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionIconNew = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/icons/Files-New-File-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIconNew.setIcon(icon1)
        self.actionIconNew.setObjectName("actionIconNew")
        self.actionIconOpen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/icons/open-file-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIconOpen.setIcon(icon2)
        self.actionIconOpen.setObjectName("actionIconOpen")
        self.actionIconSave = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/icons/Actions-document-save-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIconSave.setIcon(icon3)
        self.actionIconSave.setObjectName("actionIconSave")
        self.actionIconSaveAs = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/icons/Actions-document-save-as-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIconSaveAs.setIcon(icon4)
        self.actionIconSaveAs.setObjectName("actionIconSaveAs")
        self.actionIconHelp = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/icons/Actions-help-about-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIconHelp.setIcon(icon5)
        self.actionIconHelp.setObjectName("actionIconHelp")
        self.actionRenumerate = QtWidgets.QAction(MainWindow)
        self.actionRenumerate.setObjectName("actionRenumerate")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionFind = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Search/icons/find/Start-Menu-Search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon6)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_Next = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Search/icons/find/Search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind_Next.setIcon(icon7)
        self.actionFind_Next.setObjectName("actionFind_Next")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Search/icons/find/Actions-find-replace-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReplace.setIcon(icon8)
        self.actionReplace.setObjectName("actionReplace")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Edit/icons/edit/Actions-undo-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon9)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Edit/icons/edit/Actions-redo-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon10)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Edit/icons/edit/cut-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon11)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Edit/icons/edit/copy-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon12)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Edit/icons/edit/paste-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon13)
        self.actionPaste.setObjectName("actionPaste")
        self.actionMulti_Rename = QtWidgets.QAction(MainWindow)
        self.actionMulti_Rename.setObjectName("actionMulti_Rename")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Edit/icons/edit/Zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon14)
        self.actionZoom_In.setIconVisibleInMenu(False)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Edit/icons/edit/Zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon15)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionAdd_Row = QtWidgets.QAction(MainWindow)
        self.actionAdd_Row.setObjectName("actionAdd_Row")
        self.actionRemove_Row = QtWidgets.QAction(MainWindow)
        self.actionRemove_Row.setObjectName("actionRemove_Row")
        self.actionDeselect_All = QtWidgets.QAction(MainWindow)
        self.actionDeselect_All.setObjectName("actionDeselect_All")
        self.menuFile.addAction(self.actionIconNew)
        self.menuFile.addAction(self.actionIconOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionIconSave)
        self.menuFile.addAction(self.actionIconSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionDeselect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionZoom_In)
        self.menuEdit.addAction(self.actionZoom_Out)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_Row)
        self.menuEdit.addAction(self.actionRemove_Row)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMulti_Rename)
        #self.menuEdit.addAction(self.actionRenumerate)
        #self.menuEdit.addSeparator()
        self.menuSearch.addAction(self.actionFind)
        self.menuSearch.addAction(self.actionReplace)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionIconNew)
        self.toolBar.addAction(self.actionIconOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIconSave)
        self.toolBar.addAction(self.actionIconSaveAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_In)
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIconHelp)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "G.R.O.M."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAbout.setText(_translate("MainWindow", "About G.R.O.M."))
        self.actionIconNew.setText(_translate("MainWindow", "New"))
        self.actionIconNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionIconOpen.setText(_translate("MainWindow", "Open"))
        self.actionIconOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionIconSave.setText(_translate("MainWindow", "Save"))
        self.actionIconSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionIconSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionIconHelp.setText(_translate("MainWindow", "IconHelp"))
        self.actionIconHelp.setToolTip(_translate("MainWindow", "Show Help"))
        self.actionRenumerate.setText(_translate("MainWindow", "Renumerate"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionFind_Next.setText(_translate("MainWindow", "Find Next"))
        self.actionFind_Next.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionReplace.setText(_translate("MainWindow", "Replace"))
        self.actionReplace.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionMulti_Rename.setText(_translate("MainWindow", "Multi-Rename"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionAdd_Row.setText(_translate("MainWindow", "Add Row"))
        self.actionRemove_Row.setText(_translate("MainWindow", "Remove Row"))
        self.actionDeselect_All.setText(_translate("MainWindow", "Deselect All"))
        self.actionDeselect_All.setShortcut(_translate("MainWindow", "Alt+A"))

import Icons_rc
