# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_findreplace_qt5.ui'
#
# Created: Tue Aug 19 22:16:05 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FindAndReplaceDlg(object):
    def setupUi(self, FindAndReplaceDlg):
        FindAndReplaceDlg.setObjectName("FindAndReplaceDlg")
        FindAndReplaceDlg.setEnabled(True)
        FindAndReplaceDlg.resize(583, 443)
        FindAndReplaceDlg.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayout_2 = QtWidgets.QGridLayout(FindAndReplaceDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setSpacing(6)
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setObjectName("gridlayout")
        self.replaceLineEdit = QtWidgets.QLineEdit(FindAndReplaceDlg)
        self.replaceLineEdit.setObjectName("replaceLineEdit")
        self.gridlayout.addWidget(self.replaceLineEdit, 1, 1, 1, 1)
        self.findLineEdit = QtWidgets.QLineEdit(FindAndReplaceDlg)
        self.findLineEdit.setObjectName("findLineEdit")
        self.gridlayout.addWidget(self.findLineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(FindAndReplaceDlg)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(FindAndReplaceDlg)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.caseCheckBox = QtWidgets.QCheckBox(FindAndReplaceDlg)
        self.caseCheckBox.setObjectName("caseCheckBox")
        self.hboxlayout.addWidget(self.caseCheckBox)
        self.wholeCheckBox = QtWidgets.QCheckBox(FindAndReplaceDlg)
        self.wholeCheckBox.setEnabled(True)
        self.wholeCheckBox.setCheckable(True)
        self.wholeCheckBox.setChecked(False)
        self.wholeCheckBox.setObjectName("wholeCheckBox")
        self.hboxlayout.addWidget(self.wholeCheckBox)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_3 = QtWidgets.QLabel(FindAndReplaceDlg)
        self.label_3.setObjectName("label_3")
        self.hboxlayout1.addWidget(self.label_3)
        self.syntaxComboBox = QtWidgets.QComboBox(FindAndReplaceDlg)
        self.syntaxComboBox.setObjectName("syntaxComboBox")
        self.syntaxComboBox.addItem("")
        self.syntaxComboBox.addItem("")
        self.hboxlayout1.addWidget(self.syntaxComboBox)
        self.vboxlayout.addLayout(self.hboxlayout1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.vboxlayout, 0, 1, 2, 1)
        self.line = QtWidgets.QFrame(FindAndReplaceDlg)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 2, 3, 2)
        self.SearchPart = QtWidgets.QVBoxLayout()
        self.SearchPart.setObjectName("SearchPart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DownSearch = QtWidgets.QPushButton(FindAndReplaceDlg)
        self.DownSearch.setMinimumSize(QtCore.QSize(0, 27))
        self.DownSearch.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DownSearch.setAutoFillBackground(True)
        self.DownSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Search/icons/find/Actions-go-down-search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DownSearch.setIcon(icon)
        self.DownSearch.setIconSize(QtCore.QSize(24, 24))
        self.DownSearch.setAutoRepeat(False)
        self.DownSearch.setAutoExclusive(False)
        self.DownSearch.setObjectName("DownSearch")
        self.horizontalLayout_3.addWidget(self.DownSearch)
        self.UpSearch = QtWidgets.QPushButton(FindAndReplaceDlg)
        self.UpSearch.setMinimumSize(QtCore.QSize(0, 27))
        self.UpSearch.setFocusPolicy(QtCore.Qt.NoFocus)
        self.UpSearch.setAutoFillBackground(True)
        self.UpSearch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Search/icons/find/Actions-go-up-search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpSearch.setIcon(icon1)
        self.UpSearch.setIconSize(QtCore.QSize(24, 24))
        self.UpSearch.setAutoRepeat(False)
        self.UpSearch.setAutoExclusive(False)
        self.UpSearch.setObjectName("UpSearch")
        self.horizontalLayout_3.addWidget(self.UpSearch)
        self.findButton = QtWidgets.QPushButton(FindAndReplaceDlg)
        self.findButton.setMinimumSize(QtCore.QSize(70, 27))
        self.findButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.findButton.setObjectName("findButton")
        self.horizontalLayout_3.addWidget(self.findButton)
        self.SearchPart.addLayout(self.horizontalLayout_3)
        self.replaceButton = QtWidgets.QPushButton(FindAndReplaceDlg)
        self.replaceButton.setStatusTip("")
        self.replaceButton.setObjectName("replaceButton")
        self.SearchPart.addWidget(self.replaceButton)
        self.replaceAllButton = QtWidgets.QPushButton(FindAndReplaceDlg)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.SearchPart.addWidget(self.replaceAllButton)
        self.CoordOptionsButton = QtWidgets.QPushButton(FindAndReplaceDlg)
        self.CoordOptionsButton.setObjectName("CoordOptionsButton")
        self.SearchPart.addWidget(self.CoordOptionsButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SearchPart.addItem(spacerItem1)
        self.closeButton = QtWidgets.QPushButton(FindAndReplaceDlg)
        self.closeButton.setObjectName("closeButton")
        self.SearchPart.addWidget(self.closeButton)
        self.gridLayout_2.addLayout(self.SearchPart, 1, 3, 1, 1)
        self.frameCoord = QtWidgets.QFrame(FindAndReplaceDlg)
        self.frameCoord.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCoord.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCoord.setObjectName("frameCoord")
        self.gridLayout = QtWidgets.QGridLayout(self.frameCoord)
        self.gridLayout.setObjectName("gridLayout")
        self.CoordOptTitle = QtWidgets.QLabel(self.frameCoord)
        self.CoordOptTitle.setObjectName("CoordOptTitle")
        self.gridLayout.addWidget(self.CoordOptTitle, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxAtom = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxAtom.setObjectName("checkBoxAtom")
        self.verticalLayout_2.addWidget(self.checkBoxAtom)
        self.checkBoxSerial = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxSerial.setObjectName("checkBoxSerial")
        self.verticalLayout_2.addWidget(self.checkBoxSerial)
        self.checkBoxName = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxName.setObjectName("checkBoxName")
        self.verticalLayout_2.addWidget(self.checkBoxName)
        self.checkBoxResName = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxResName.setObjectName("checkBoxResName")
        self.verticalLayout_2.addWidget(self.checkBoxResName)
        self.checkBoxChainID = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxChainID.setObjectName("checkBoxChainID")
        self.verticalLayout_2.addWidget(self.checkBoxChainID)
        self.checkBoxResSeq = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxResSeq.setObjectName("checkBoxResSeq")
        self.verticalLayout_2.addWidget(self.checkBoxResSeq)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxX = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxX.setObjectName("checkBoxX")
        self.verticalLayout_3.addWidget(self.checkBoxX)
        self.checkBoxY = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxY.setObjectName("checkBoxY")
        self.verticalLayout_3.addWidget(self.checkBoxY)
        self.checkBoxZ = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxZ.setObjectName("checkBoxZ")
        self.verticalLayout_3.addWidget(self.checkBoxZ)
        self.checkBoxOccup = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxOccup.setObjectName("checkBoxOccup")
        self.verticalLayout_3.addWidget(self.checkBoxOccup)
        self.checkBoxTempFact = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxTempFact.setObjectName("checkBoxTempFact")
        self.verticalLayout_3.addWidget(self.checkBoxTempFact)
        self.checkBoxElem = QtWidgets.QCheckBox(self.frameCoord)
        self.checkBoxElem.setObjectName("checkBoxElem")
        self.verticalLayout_3.addWidget(self.checkBoxElem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_AllColumns = QtWidgets.QPushButton(self.frameCoord)
        self.pushButton_AllColumns.setObjectName("pushButton_AllColumns")
        self.horizontalLayout.addWidget(self.pushButton_AllColumns)
        self.pushButton_NoColumns = QtWidgets.QPushButton(self.frameCoord)
        self.pushButton_NoColumns.setObjectName("pushButton_NoColumns")
        self.horizontalLayout.addWidget(self.pushButton_NoColumns)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameCoord, 2, 0, 1, 2)
        self.label_2.setBuddy(self.replaceLineEdit)
        self.label.setBuddy(self.findLineEdit)
        self.label_3.setBuddy(self.syntaxComboBox)

        self.retranslateUi(FindAndReplaceDlg)
        self.closeButton.clicked.connect(FindAndReplaceDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(FindAndReplaceDlg)
        FindAndReplaceDlg.setTabOrder(self.findLineEdit, self.replaceLineEdit)
        FindAndReplaceDlg.setTabOrder(self.replaceLineEdit, self.caseCheckBox)
        FindAndReplaceDlg.setTabOrder(self.caseCheckBox, self.wholeCheckBox)
        FindAndReplaceDlg.setTabOrder(self.wholeCheckBox, self.syntaxComboBox)
        FindAndReplaceDlg.setTabOrder(self.syntaxComboBox, self.replaceButton)
        FindAndReplaceDlg.setTabOrder(self.replaceButton, self.closeButton)

    def retranslateUi(self, FindAndReplaceDlg):
        _translate = QtCore.QCoreApplication.translate
        FindAndReplaceDlg.setWindowTitle(_translate("FindAndReplaceDlg", "Find and Replace"))
        self.label_2.setText(_translate("FindAndReplaceDlg", "Replace w&ith:"))
        self.label.setText(_translate("FindAndReplaceDlg", "Find &what:"))
        self.caseCheckBox.setText(_translate("FindAndReplaceDlg", "&Case sensitive"))
        self.wholeCheckBox.setText(_translate("FindAndReplaceDlg", "Wh&ole words"))
        self.label_3.setText(_translate("FindAndReplaceDlg", "&Syntax:"))
        self.syntaxComboBox.setItemText(0, _translate("FindAndReplaceDlg", "Literal text"))
        self.syntaxComboBox.setItemText(1, _translate("FindAndReplaceDlg", "Regular expression"))
        self.DownSearch.setToolTip(_translate("FindAndReplaceDlg", "Find Next"))
        self.UpSearch.setToolTip(_translate("FindAndReplaceDlg", "Find Previous"))
        self.findButton.setToolTip(_translate("FindAndReplaceDlg", "Find All"))
        self.findButton.setStatusTip(_translate("FindAndReplaceDlg", "Find All"))
        self.findButton.setText(_translate("FindAndReplaceDlg", "&Find All"))
        self.replaceButton.setText(_translate("FindAndReplaceDlg", "&Replace"))
        self.replaceAllButton.setText(_translate("FindAndReplaceDlg", "Replace &All"))
        self.CoordOptionsButton.setText(_translate("FindAndReplaceDlg", "Coord Options"))
        self.closeButton.setText(_translate("FindAndReplaceDlg", "Close"))
        self.CoordOptTitle.setText(_translate("FindAndReplaceDlg", "Coordinate Search Options"))
        self.checkBoxAtom.setText(_translate("FindAndReplaceDlg", "\"ATOM \""))
        self.checkBoxSerial.setText(_translate("FindAndReplaceDlg", "serial "))
        self.checkBoxName.setText(_translate("FindAndReplaceDlg", "name "))
        self.checkBoxResName.setText(_translate("FindAndReplaceDlg", "resName "))
        self.checkBoxChainID.setText(_translate("FindAndReplaceDlg", "chainID "))
        self.checkBoxResSeq.setText(_translate("FindAndReplaceDlg", "resSeq "))
        self.checkBoxX.setText(_translate("FindAndReplaceDlg", "x "))
        self.checkBoxY.setText(_translate("FindAndReplaceDlg", "y"))
        self.checkBoxZ.setText(_translate("FindAndReplaceDlg", "z"))
        self.checkBoxOccup.setText(_translate("FindAndReplaceDlg", "occupancy"))
        self.checkBoxTempFact.setText(_translate("FindAndReplaceDlg", "tempFactor "))
        self.checkBoxElem.setText(_translate("FindAndReplaceDlg", "element"))
        self.pushButton_AllColumns.setText(_translate("FindAndReplaceDlg", "All Columns"))
        self.pushButton_NoColumns.setText(_translate("FindAndReplaceDlg", "No Columns"))

import Icons_rc
